title: "Cyril Joly - Machine Learning Engineer"
description: "Site personnel de présentation de Cyril Joly, ingénieur spécialisé en machine learning."
baseurl: ""
url: "https://CyrilJl.github.io"
theme: minima