name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo
      - name: Build
        run: hugo --minify --baseURL "https://cyriljl.github.io/website"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public